## Add default values for the dependencies charts here, if included, available at ./charts.
## Include the name of the dependency as a top-level key to overrides those values.

label-studio:
  global:
    extraEnvironmentVars:
      LABEL_STUDIO_HOST: "PLACEHOLDER"

  app:
    contextPath: "/label-studio"
    nginx:
      livenessProbe:
        path: "/label-studio/health"


## Add default values for this Chart and Kubernetes resources in the ./templates directory.
## Update the overrides key in the nebari-config.yaml to modify these values.

startup_greeting: "Try overriding this from the nebari-config.yaml"
# Try:
# my-label-studio:
#   overrides:
#     startup_greeting: Did I do it?

ingress:
  enabled: true
  host: "PLACEHOLDER"
  path: /label-studio

auth:
  enabled: true
  image: thomseddon/traefik-forward-auth
  tag: "2"
  service:
    port: 4181

logLevel: info
