{{- if .Values.auth.enabled }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      containers:
      - image: {{ .Values.auth.image }}:{{ .Values.auth.tag }}
        name: main
        ports:
        - containerPort: 4181
          protocol: TCP
          name: http
        env:
        - name: LOG_LEVEL
          value: {{ .Values.logLevel }}
        - name: INSECURE_COOKIE
          value: "false"
        - name: URL_PATH
          value: {{ .Values.ingress.path }}/_oauth
        - name: PROVIDERS_OIDC_ISSUER_URL
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-env
              key: issuer_url
        - name: PROVIDERS_OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-env
              key: client_id
        - name: PROVIDERS_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-env
              key: client_secret
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth-env
              key: signing_key
        - name: DEFAULT_PROVIDER
          value: "oidc"

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: traefik-forward-auth
  ports:
  - port: {{ .Values.auth.service.port }}
    targetPort: http
    protocol: TCP
    name: http

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
  namespace: {{ .Release.Namespace }}
spec:
  forwardAuth:
    address: http://traefik-forward-auth.{{ .Release.Namespace }}:{{ .Values.auth.service.port }}/
    authResponseHeaders:
    - X-Forwarded-User

{{- end }}
