# Add your Kubernetes resources here, supports Jinja2 templating and set default values in values.yaml

---
apiVersion: batch/v1
kind: Job
metadata:
  name: greetings-from-the-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        args:
        - /bin/sh
        - -c
        - echo "{{ .Values.startup_greeting }}"; sleep 30
      restartPolicy: Never
